/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. */
/* Generated by: documentation/scripts/count-home-hero-stats.mjs */

export type HeroStat = { value: string; label: string; href: string };

export const heroStats: HeroStat[] = [
    {
        "value": "89",
        "label": "Components",
        "href": "/components/ui/Button"
    },
    {
        "value": "43",
        "label": "Charts",
        "href": "/charts/overview"
    },
    {
        "value": "26",
        "label": "Blocks",
        "href": "/blocks/installation"
    },
    {
        "value": "8",
        "label": "Smart Tools",
        "href": "/smart-tools/installation"
    },
    {
        "value": "168",
        "label": "Assets",
        "href": "/assets/icons"
    },
    {
        "value": "8",
        "label": "MCP Tools",
        "href": "/ai/overview"
    }
];
